const ELEMENTS = {
  // ── 第一层：基础元素 ──────────────────────────────────────────
  快乐: { tier: 1, color: '#FFD700', glow: '#FFA500', desc: '心中升起的暖意', emoji: '☀' },
  悲伤: { tier: 1, color: '#6CA0DC', glow: '#4169E1', desc: '流不完的泪，说不清的重', emoji: '🌧' },
  愤怒: { tier: 1, color: '#FF4444', glow: '#CC0000', desc: '胸腔里烧着的那团火', emoji: '🔥' },
  时间: { tier: 1, color: '#C0C0C0', glow: '#E8E8E8', desc: '唯一公平的东西，也是最残忍的', emoji: '⏳' },
  思念: { tier: 1, color: '#B39DDB', glow: '#9C27B0', desc: '某个名字压在心底', emoji: '🌙' },
  孤独: { tier: 1, color: '#78909C', glow: '#546E7A', desc: '人群里最安静的那个人', emoji: '🕯' },
  恐惧: { tier: 1, color: '#37474F', glow: '#263238', desc: '看不见的东西最可怕', emoji: '🌑' },
  期待: { tier: 1, color: '#81C784', glow: '#4CAF50', desc: '明天一定会不一样', emoji: '🌱' },
  爱: { tier: 1, color: '#F48FB1', glow: '#E91E63', desc: '无法解释，但真实存在', emoji: '💫' },
  遗忘: { tier: 1, color: '#ECEFF1', glow: '#B0BEC5', desc: '有些事，记不清了', emoji: '🌫' },

  // ── 第二层：情绪词 ────────────────────────────────────────────
  释怀: { tier: 2, color: '#80DEEA', glow: '#26C6DA', desc: '伤口被时间慢慢填平' },
  怀念: { tier: 2, color: '#FFCC80', glow: '#FFA726', desc: '回不去的才叫美好' },
  煎熬: { tier: 2, color: '#CE93D8', glow: '#AB47BC', desc: '等待让思念发酵' },
  委屈: { tier: 2, color: '#90CAF9', glow: '#42A5F5', desc: '怒火散了，只剩心酸' },
  释然: { tier: 2, color: '#A5D6A7', glow: '#66BB6A', desc: '淡了，也就好了' },
  绝望: { tier: 2, color: '#424242', glow: '#212121', desc: '看不到尽头的害怕' },
  焦虑: { tier: 2, color: '#FFAB91', glow: '#FF7043', desc: '等待让人心神不宁' },
  深情: { tier: 2, color: '#F48FB1', glow: '#EC407A', desc: '爱因时间沉淀而厚重' },
  空洞: { tier: 2, color: '#546E7A', glow: '#37474F', desc: '一个人待太久，连感觉都没了' },
  复杂: { tier: 2, color: '#9FA8DA', glow: '#7986CB', desc: '哭着笑，或笑着哭' },
  自由: { tier: 2, color: '#80CBC4', glow: '#26A69A', desc: '一个人也可以很好' },
  心动: { tier: 2, color: '#F8BBD0', glow: '#F06292', desc: '想到那个人就会笑' },
  雀跃: { tier: 2, color: '#DCEDC8', glow: '#AED581', desc: '明天一定会更好' },
  幸福: { tier: 2, color: '#FFF9C4', glow: '#FFF176', desc: '此刻，刚刚好' },
  天真: { tier: 2, color: '#E1F5FE', glow: '#81D4FA', desc: '不记得烦恼的轻盈' },
  遗憾: { tier: 2, color: '#BCAAA4', glow: '#8D6E63', desc: '来不及说的那句话' },
  落寞: { tier: 2, color: '#78909C', glow: '#546E7A', desc: '人群里最安静的那个人' },
  心疼: { tier: 2, color: '#EF9A9A', glow: '#EF5350', desc: '因为在乎才会痛' },
  崩溃: { tier: 2, color: '#B71C1C', glow: '#7F0000', desc: '撑不住的那一刻' },
  麻木: { tier: 2, color: '#616161', glow: '#424242', desc: '哭不出来了' },
  失落: { tier: 2, color: '#90A4AE', glow: '#607D8B', desc: '以为会不同，但还是这样' },
  嫉妒: { tier: 2, color: '#A5D6A7', glow: '#388E3C', desc: '因为爱才计较' },
  倔强: { tier: 2, color: '#FF8A65', glow: '#F4511E', desc: '一个人扛着，不说' },
  痛苦: { tier: 2, color: '#D32F2F', glow: '#B71C1C', desc: '伤到极处，化为怒火' },
  暴躁: { tier: 2, color: '#FF6D00', glow: '#E65100', desc: '用攻击掩盖脆弱' },
  相思: { tier: 2, color: '#CE93D8', glow: '#9C27B0', desc: '千里共婵娟却无法相见' },
  模糊: { tier: 2, color: '#CFD8DC', glow: '#90A4AE', desc: '记不清脸了，但还在想' },
  牵挂: { tier: 2, color: '#F48FB1', glow: '#E91E63', desc: '放不下的挂念' },
  忐忑: { tier: 2, color: '#FFE082', glow: '#FFD740', desc: '又想要，又怕失去' },
  暗恋: { tier: 2, color: '#F8BBD0', glow: '#FF80AB', desc: '不敢说出口的喜欢' },
  虚无: { tier: 2, color: '#263238', glow: '#102027', desc: '什么都不剩的空' },
  守候: { tier: 2, color: '#B39DDB', glow: '#7E57C2', desc: '一个人等着另一个人' },

  // ── 第三层：抽象概念 ──────────────────────────────────────────
  放下: { tier: 3, color: '#80DEEA', glow: '#00BCD4', desc: '不是不爱了，是学会了带着爱离开' },
  执念: { tier: 3, color: '#9575CD', glow: '#673AB7', desc: '反复回到那个时刻' },
  错过: { tier: 3, color: '#A1887F', glow: '#795548', desc: '最好的时候没有在一起' },
  珍惜: { tier: 3, color: '#FFD54F', glow: '#FFC107', desc: '怕失去，所以更用心握着' },
  洒脱: { tier: 3, color: '#80CBC4', glow: '#009688', desc: '走到哪里都是家' },
  望穿秋水: { tier: 3, color: '#90CAF9', glow: '#2196F3', desc: '眼泪都等干了' },
  单相思: { tier: 3, color: '#F48FB1', glow: '#E91E63', desc: '一个人的热闹' },
  重生: { tier: 3, color: '#FFCC80', glow: '#FF9800', desc: '碎过一次，才知道自己多坚韧' },
  成熟: { tier: 3, color: '#A5D6A7', glow: '#4CAF50', desc: '不再非黑即白' },
  迷茫: { tier: 3, color: '#B0BEC5', glow: '#78909C', desc: '不知道自己要什么' },
  从容: { tier: 3, color: '#E1F5FE', glow: '#03A9F4', desc: '什么都经历过，所以什么都不怕' },
  释梦: { tier: 3, color: '#CE93D8', glow: '#9C27B0', desc: '终于肯让那个梦醒了' },
  忠诚: { tier: 3, color: '#FFD700', glow: '#FFC200', desc: '等你，不管多久' },
  祝福: { tier: 3, color: '#A5D6A7', glow: '#66BB6A', desc: '希望你好，即使没有我' },
  爱意: { tier: 3, color: '#FF80AB', glow: '#FF4081', desc: '说不出口，但藏不住' },
  淡然: { tier: 3, color: '#CFD8DC', glow: '#90A4AE', desc: '热闹是他们的，我什么都没有——但也无所谓' },
  清醒: { tier: 3, color: '#E8F5E9', glow: '#81C784', desc: '看透了，但还是善良' },
  挣扎: { tier: 3, color: '#FF8A65', glow: '#FF5722', desc: '还没完全放弃' },
  缘分: { tier: 3, color: '#F8BBD0', glow: '#F06292', desc: '来过就好' },
  平淡: { tier: 3, color: '#ECEFF1', glow: '#CFD8DC', desc: '原来爱到最后都是柴米油盐' },
  悲悯: { tier: 3, color: '#80CBC4', glow: '#26A69A', desc: '因为懂得，所以慈悲' },
  豁达: { tier: 3, color: '#FFF9C4', glow: '#FFF176', desc: '人生没什么大不了的' },
  沧桑: { tier: 3, color: '#8D6E63', glow: '#6D4C41', desc: '经历过太多，眼神里有故事' },
  温柔: { tier: 3, color: '#F48FB1', glow: '#F06292', desc: '不是软弱，是选择了善意' },

  // ── 第四层：古诗词 ────────────────────────────────────────────
  此情可待成追忆: {
    tier: 4,
    color: '#E8D5F5',
    glow: '#9C27B0',
    isPoem: true,
    poem: '此情可待成追忆，只是当时已惘然',
    author: '李商隐·《锦瑟》',
    context: '写给一段无法言说的感情。那些最深的情，往往要回头才懂，当时只道是寻常。',
    particles: 'purple'
  },
  红豆相思: {
    tier: 4,
    color: '#FFCDD2',
    glow: '#F44336',
    isPoem: true,
    poem: '红豆生南国，春来发几枝。愿君多采撷，此物最相思。',
    author: '王维·《相思》',
    context: '送别友人所作，以红豆寄相思之情。简单四句，道尽天下离别。',
    particles: 'red'
  },
  人生若只如初见: {
    tier: 4,
    color: '#E1BEE7',
    glow: '#9C27B0',
    isPoem: true,
    poem: '人生若只如初见，何事秋风悲画扇。',
    author: '纳兰性德·《木兰花令》',
    context: '感叹相识容易、相守太难。若一切停在最初的美好，该多好。',
    particles: 'purple'
  },
  采菊东篱: {
    tier: 4,
    color: '#DCEDC8',
    glow: '#8BC34A',
    isPoem: true,
    poem: '采菊东篱下，悠然见南山。',
    author: '陶渊明·《饮酒·其五》',
    context: '辞官归隐后所作。不是消极，是真正找到了自己想要的生活方式。',
    particles: 'green'
  },
  我住长江头: {
    tier: 4,
    color: '#B3E5FC',
    glow: '#03A9F4',
    isPoem: true,
    poem: '我住长江头，君住长江尾。日日思君不见君，共饮长江水。',
    author: '李之仪·《卜算子》',
    context: '两地相隔，却共饮一江水。距离再远，也有连结。',
    particles: 'blue'
  },
  仰天大笑出门去: {
    tier: 4,
    color: '#FFF9C4',
    glow: '#FFEB3B',
    isPoem: true,
    poem: '仰天大笑出门去，我辈岂是蓬蒿人。',
    author: '李白·《南陵别儿童入京》',
    context: '得到皇帝召见时所作，意气风发，以为终于可以施展抱负。',
    particles: 'gold'
  },
  月上柳梢头: {
    tier: 4,
    color: '#FFF8E1',
    glow: '#FFD740',
    isPoem: true,
    poem: '月上柳梢头，人约黄昏后。',
    author: '欧阳修·《生查子·元夕》',
    context: '写元宵节的相约。美好短暂，而今灯火依旧，人却不同。',
    particles: 'gold'
  },
  比翼连理: {
    tier: 4,
    color: '#FCE4EC',
    glow: '#E91E63',
    isPoem: true,
    poem: '在天愿作比翼鸟，在地愿为连理枝。',
    author: '白居易·《长恨歌》',
    context: '写李隆基与杨贵妃的爱情，山盟海誓，却终究天人永隔。',
    particles: 'pink'
  },
  一江春水向东流: {
    tier: 4,
    color: '#B2EBF2',
    glow: '#00BCD4',
    isPoem: true,
    poem: '问君能有几多愁，恰似一江春水向东流。',
    author: '李煜·《虞美人》',
    context: '亡国之君被囚禁时所作，愁绪如江水滔滔无尽，写完此词不久即被毒杀。',
    particles: 'blue'
  },
  千淘万漉始到金: {
    tier: 4,
    color: '#FFF8E1',
    glow: '#FFB300',
    isPoem: true,
    poem: '千淘万漉虽辛苦，吹尽狂沙始到金。',
    author: '刘禹锡·《浪淘沙》',
    context: '屡遭贬谪二十三年，却始终不屈。用淘金自比，苦尽才能甘来。',
    particles: 'gold'
  },
  灯火阑珊处: {
    tier: 4,
    color: '#FCE4EC',
    glow: '#FF4081',
    isPoem: true,
    poem: '众里寻他千百度，蓦然回首，那人却在，灯火阑珊处。',
    author: '辛弃疾·《青玉案·元夕》',
    context: '表面写元宵寻人，实则写历经千辛万苦，蓦然发现所求之物早已在身边。',
    particles: 'pink'
  },
  西窗剪烛: {
    tier: 4,
    color: '#FFF3E0',
    glow: '#FF9800',
    isPoem: true,
    poem: '何当共剪西窗烛，却话巴山夜雨时。',
    author: '李商隐·《夜雨寄北》',
    context: '身在异乡，妻子来信问归期，想象与妻子重聚的那一天，共话今夜的相思。',
    particles: 'orange'
  },
  千里共婵娟: {
    tier: 4,
    color: '#E8EAF6',
    glow: '#5C6BC0',
    isPoem: true,
    poem: '但愿人长久，千里共婵娟。',
    author: '苏轼·《水调歌头》',
    context: '中秋思念弟弟苏辙，把无法相聚的遗憾化为最美的祝愿，月亮是他们共同的牵挂。',
    particles: 'indigo'
  },
  所谓伊人在水一方: {
    tier: 4,
    color: '#E0F7FA',
    glow: '#00BCD4',
    isPoem: true,
    poem: '蒹葭苍苍，白露为霜。所谓伊人，在水一方。',
    author: '《诗经·蒹葭》',
    context: '追寻心中那个人，隔着茫茫芦苇与流水，可望而不可即，是最古老的暗恋。',
    particles: 'cyan'
  },
  衣带渐宽终不悔: {
    tier: 4,
    color: '#FCE4EC',
    glow: '#F06292',
    isPoem: true,
    poem: '衣带渐宽终不悔，为伊消得人憔悴。',
    author: '柳永·《蝶恋花》',
    context: '为思念的人，消瘦了也心甘情愿。这种执迷不悔，是爱最极致的样子。',
    particles: 'pink'
  },
  独坐幽篁: {
    tier: 4,
    color: '#E8F5E9',
    glow: '#4CAF50',
    isPoem: true,
    poem: '独坐幽篁里，弹琴复长啸。深林人不知，明月来相照。',
    author: '王维·《竹里馆》',
    context: '晚年隐居辋川，一个人在竹林里弹琴，不需要任何人，月亮就是知己。',
    particles: 'green'
  },
  春蚕到死丝方尽: {
    tier: 4,
    color: '#FCE4EC',
    glow: '#E91E63',
    isPoem: true,
    poem: '春蚕到死丝方尽，蜡炬成灰泪始干。',
    author: '李商隐·《无题》',
    context: '写两情相悦却无法相聚的痛苦。这种爱，至死方休。',
    particles: 'pink'
  },
  举杯邀明月: {
    tier: 4,
    color: '#E8EAF6',
    glow: '#7986CB',
    isPoem: true,
    poem: '举杯邀明月，对影成三人。',
    author: '李白·《月下独酌》',
    context: '一个人喝酒，邀请月亮和影子作陪。孤独到极处，反而活出了浪漫。',
    particles: 'indigo'
  },
  莫道桑榆晚: {
    tier: 4,
    color: '#FFF8E1',
    glow: '#FFB300',
    isPoem: true,
    poem: '莫道桑榆晚，为霞尚满天。',
    author: '刘禹锡·《酬乐天咏老见示》',
    context: '以霞光满天比喻老年仍可有所作为。屡经磨难，却始终向阳而生。',
    particles: 'gold'
  },
  曾经沧海难为水: {
    tier: 4,
    color: '#E0F7FA',
    glow: '#0097A7',
    isPoem: true,
    poem: '曾经沧海难为水，除却巫山不是云。',
    author: '元稹·《离思》',
    context: '悼念亡妻所作，见过最深的爱，其他一切都黯然失色。',
    particles: 'cyan'
  },
  十年生死两茫茫: {
    tier: 4,
    color: '#ECEFF1',
    glow: '#90A4AE',
    isPoem: true,
    poem: '十年生死两茫茫，不思量，自难忘。',
    author: '苏轼·《江城子·乙卯正月二十日夜记梦》',
    context: '悼念亡妻王弗，梦中相见，泪流满面。是中国最动人的悼亡词之一。',
    particles: 'gray'
  },
  天生我材必有用: {
    tier: 4,
    color: '#FFF9C4',
    glow: '#F9A825',
    isPoem: true,
    poem: '天生我材必有用，千金散尽还复来。',
    author: '李白·《将进酒》',
    context: '与友人痛饮时所作，豪迈洒脱，即使落魄也相信自己的价值。',
    particles: 'gold'
  },
  身无彩凤双飞翼: {
    tier: 4,
    color: '#F3E5F5',
    glow: '#9C27B0',
    isPoem: true,
    poem: '身无彩凤双飞翼，心有灵犀一点通。',
    author: '李商隐·《无题》',
    context: '写两人虽不能相聚，但心意相通，这种默契胜过千言万语。',
    particles: 'purple'
  },
  长风破浪会有时: {
    tier: 4,
    color: '#E3F2FD',
    glow: '#1976D2',
    isPoem: true,
    poem: '长风破浪会有时，直挂云帆济沧海。',
    author: '李白·《行路难》',
    context: '仕途受阻、理想难展之时所作，但李白始终相信，终有一天能乘风破浪。',
    particles: 'blue'
  },
  不识庐山真面目: {
    tier: 4,
    color: '#E8F5E9',
    glow: '#388E3C',
    isPoem: true,
    poem: '不识庐山真面目，只缘身在此山中。',
    author: '苏轼·《题西林壁》',
    context: '游庐山有感，说的是山，也是人生——身在局中，难以看清全貌。',
    particles: 'green'
  },
  海内存知己: {
    tier: 4,
    color: '#E8EAF6',
    glow: '#3F51B5',
    isPoem: true,
    poem: '海内存知己，天涯若比邻。',
    author: '王勃·《送杜少府之任蜀州》',
    context: '送别友人赴任，以此句宽慰，真正的友情不因距离而减淡。',
    particles: 'indigo'
  },
  会当凌绝顶: {
    tier: 4,
    color: '#FFF8E1',
    glow: '#FFC107',
    isPoem: true,
    poem: '会当凌绝顶，一览众山小。',
    author: '杜甫·《望岳》',
    context: '年轻时游泰山所作，壮志凌云，相信终有一天能登上人生的顶峰。',
    particles: 'gold'
  },
  桃花潭水深千尺: {
    tier: 4,
    color: '#FCE4EC',
    glow: '#E91E63',
    isPoem: true,
    poem: '桃花潭水深千尺，不及汪伦送我情。',
    author: '李白·《赠汪伦》',
    context: '朋友汪伦以歌声送别，李白即兴写下此诗，情深意重，千古传诵。',
    particles: 'pink'
  },
  夕阳无限好: {
    tier: 4,
    color: '#FBE9E7',
    glow: '#FF7043',
    isPoem: true,
    poem: '夕阳无限好，只是近黄昏。',
    author: '李商隐·《乐游原》',
    context: '登高远望，夕阳美得令人心痛，却也即将消逝。美好之物，总在消逝前最动人。',
    particles: 'orange'
  },
  醉卧沙场君莫笑: {
    tier: 4,
    color: '#EDE7F6',
    glow: '#673AB7',
    isPoem: true,
    poem: '醉卧沙场君莫笑，古来征战几人回。',
    author: '王翰·《凉州词》',
    context: '出征前夕，与战友痛饮。不是不知道危险，是选择了以豪迈面对生死。',
    particles: 'purple'
  },
  春色满园关不住: {
    tier: 4,
    color: '#E8F5E9',
    glow: '#66BB6A',
    isPoem: true,
    poem: '春色满园关不住，一枝红杏出墙来。',
    author: '叶绍翁·《游园不值》',
    context: '叩门不遇，却见一枝红杏探出墙来。生命力无法压制，美好总会找到出口。',
    particles: 'green'
  },
};

// ── 组合规则 ──────────────────────────────────────────────────
const COMBINATIONS = [
  // 第一层 → 第二层
  ['时间', '悲伤', '释怀'],
  ['时间', '快乐', '怀念'],
  ['时间', '思念', '煎熬'],
  ['时间', '愤怒', '委屈'],
  ['时间', '遗忘', '释然'],
  ['时间', '恐惧', '绝望'],
  ['时间', '期待', '焦虑'],
  ['时间', '爱', '深情'],
  ['时间', '孤独', '空洞'],
  ['快乐', '悲伤', '复杂'],
  ['快乐', '孤独', '自由'],
  ['快乐', '思念', '心动'],
  ['快乐', '期待', '雀跃'],
  ['快乐', '爱', '幸福'],
  ['快乐', '遗忘', '天真'],
  ['悲伤', '思念', '遗憾'],
  ['悲伤', '孤独', '落寞'],
  ['悲伤', '爱', '心疼'],
  ['悲伤', '恐惧', '崩溃'],
  ['悲伤', '遗忘', '麻木'],
  ['悲伤', '期待', '失落'],
  ['愤怒', '爱', '嫉妒'],
  ['愤怒', '孤独', '倔强'],
  ['愤怒', '悲伤', '痛苦'],
  ['愤怒', '恐惧', '暴躁'],
  ['思念', '孤独', '相思'],
  ['思念', '遗忘', '模糊'],
  ['思念', '爱', '牵挂'],
  ['期待', '恐惧', '忐忑'],
  ['期待', '爱', '暗恋'],
  ['孤独', '遗忘', '虚无'],
  ['孤独', '爱', '守候'],
  ['遗忘', '爱', '释然'],
  ['恐惧', '爱', '珍惜'],

  // 第二层 → 第三层
  ['释怀', '思念', '放下'],
  ['怀念', '遗憾', '执念'],
  ['深情', '遗憾', '错过'],
  ['幸福', '恐惧', '珍惜'],
  ['自由', '孤独', '洒脱'],
  ['相思', '煎熬', '望穿秋水'],
  ['暗恋', '时间', '单相思'],
  ['崩溃', '时间', '重生'],
  ['复杂', '时间', '成熟'],
  ['虚无', '期待', '迷茫'],
  ['放下', '自由', '从容'],
  ['执念', '遗忘', '释梦'],
  ['守候', '煎熬', '忠诚'],
  ['牵挂', '释怀', '祝福'],
  ['心动', '忐忑', '爱意'],
  ['落寞', '洒脱', '淡然'],
  ['天真', '成熟', '清醒'],
  ['麻木', '期待', '挣扎'],
  ['错过', '放下', '缘分'],
  ['幸福', '时间', '平淡'],
  ['心疼', '释怀', '悲悯'],
  ['释然', '洒脱', '豁达'],
  ['委屈', '时间', '沧桑'],
  ['深情', '温柔', '温柔'],
  ['心动', '爱', '爱意'],
  ['遗憾', '爱', '牵挂'],
  ['失落', '期待', '挣扎'],
  ['嫉妒', '爱', '深情'],
  ['倔强', '时间', '沧桑'],
  ['焦虑', '释怀', '淡然'],

  // 第三层 → 第四层（古诗词）
  ['执念', '时间', '此情可待成追忆'],
  ['相思', '时间', '红豆相思'],
  ['放下', '时间', '人生若只如初见'],
  ['从容', '平淡', '采菊东篱'],
  ['错过', '煎熬', '我住长江头'],
  ['洒脱', '自由', '仰天大笑出门去'],
  ['守候', '遗憾', '月上柳梢头'],
  ['忠诚', '爱', '比翼连理'],
  ['迷茫', '时间', '一江春水向东流'],
  ['重生', '从容', '千淘万漉始到金'],
  ['清醒', '爱意', '灯火阑珊处'],
  ['牵挂', '平淡', '西窗剪烛'],
  ['祝福', '缘分', '千里共婵娟'],
  ['暗恋', '时间', '所谓伊人在水一方'],
  ['崩溃', '爱', '衣带渐宽终不悔'],
  ['孤独', '从容', '独坐幽篁'],
  ['执念', '爱', '春蚕到死丝方尽'],
  ['孤独', '洒脱', '举杯邀明月'],
  ['重生', '豁达', '莫道桑榆晚'],
  ['深情', '沧桑', '曾经沧海难为水'],
  ['思念', '沧桑', '十年生死两茫茫'],
  ['豁达', '自由', '天生我材必有用'],
  ['爱意', '温柔', '身无彩凤双飞翼'],
  ['迷茫', '重生', '长风破浪会有时'],
  ['成熟', '清醒', '不识庐山真面目'],
  ['祝福', '缘分', '海内存知己'],
  ['期待', '重生', '会当凌绝顶'],
  ['爱意', '缘分', '桃花潭水深千尺'],
  ['沧桑', '释然', '夕阳无限好'],
  ['洒脱', '忠诚', '醉卧沙场君莫笑'],
  ['重生', '期待', '春色满园关不住'],
  // 诗词 + 情感 → 更深的诗词（跨诗组合）
  ['此情可待成追忆', '守候', '十年生死两茫茫'],
  ['红豆相思', '时间', '所谓伊人在水一方'],
  ['千里共婵娟', '遗憾', '月上柳梢头'],
  ['采菊东篱', '孤独', '独坐幽篁'],
  ['灯火阑珊处', '爱意', '身无彩凤双飞翼'],
];

// 俏皮提示语
const FAIL_MESSAGES = [
  '这两种情绪还没有找到彼此…',
  '嗯…它们还不认识，再试试别的？',
  '有些情感，需要更多时间发酵。',
  '这两个放在一起，产生了沉默。',
  '也许它们在平行宇宙里相遇了。',
  '宇宙摇了摇头。',
  '什么都没发生，但你的心动了吗？',
  '它们相遇了，却说不出话来。',
  '也许还缺少一点点什么。',
  '有时候，有些情感无法组合，就像有些缘分，无法强求。',
];

if (typeof module !== 'undefined') {
  module.exports = { ELEMENTS, COMBINATIONS, FAIL_MESSAGES };
}
